# ---------------------------------------------------------------------------------------------
# RL_PtG: Deep Reinforcement Learning for Power-to-Gas Dispatch Optimization
# https://github.com/SimMarkt/RL_PtG

# config_train:
# > Configuration file for setting up training
# ---------------------------------------------------------------------------------------------

com_conf : pc  # Computational resources: 'pc' (local) or 'slurm' (SLURM cluster)

# Computational device to use: ['cpu', 'cuda', 'auto']
# 'auto' selects GPU if available, otherwise defaults to CPU
device : auto

str_inv : train  # Specifies the training results and models for a specific investigation

# Model config: 'simple_train', 'save_model', 'load_model', 'save_load_model'
# 'simple_train': Train the RL model from scratch
# 'save_model': Train the RL model from scratch and save it afterward
# 'load_model': Load a pretrained RL model and continue training
# 'save_load_model': Load a pretrained RL model, continue training, and save the updated model
model_conf : simple_train

path_files : /logs/  # Path where pretrained RL models and logs are stored

# Parallel execution setup:
# - "Singleprocessing" (DummyVecEnv): sequential, for fast envs (e.g., ptg_gym_env.py)
# - "Multiprocessing" (SubprocVecEnv): parallel, for intensive envs
parallel : Singleprocessing

# train_or_eval: Specifies the mode of operation, whether training or evaluation:
# - "eval": Provides detailed state descriptions for evaluation purposes.
# - "train": Default setting for training; does not provide detailed state descriptions.
train_or_eval : train

eval_trials : 5     # No. of evaluation trials for validation/testing.
val_n_test : False  # True: evaluate on validation and test sets; False: only validation 

train_steps : 1500000  # No. of training steps
test_steps : 20000     # Validation interval: No. of steps between evaluations during training

# Random seeds for reproducibility of neural network initialization and environment randomness:
r_seed_train : [3654, 467, 9327, 5797, 249, 9419]  # for training (default: [3654] for single-threaded computations)
r_seed_test : [605, 5534, 2910, 7653, 8936, 1925]  # for validation (default: [605] for single-threaded computations)